//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atomic.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Text_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Atomic.Language.Text_fr", typeof(Text_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        internal static string ModNotes {
            get {
                return ResourceManager.GetString("ModNotes", resourceCulture);
            }
        }
        
        internal static string UsesCustomSaves {
            get {
                return ResourceManager.GetString("UsesCustomSaves", resourceCulture);
            }
        }
        
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        internal static string UsesCustomMusic {
            get {
                return ResourceManager.GetString("UsesCustomMusic", resourceCulture);
            }
        }
        
        internal static string UsesYYC {
            get {
                return ResourceManager.GetString("UsesYYC", resourceCulture);
            }
        }
        
        internal static string SupportsWindows {
            get {
                return ResourceManager.GetString("SupportsWindows", resourceCulture);
            }
        }
        
        internal static string LoadWindowsZip {
            get {
                return ResourceManager.GetString("LoadWindowsZip", resourceCulture);
            }
        }
        
        internal static string WindowsLoaded {
            get {
                return ResourceManager.GetString("WindowsLoaded", resourceCulture);
            }
        }
        
        internal static string BundleAndroid {
            get {
                return ResourceManager.GetString("BundleAndroid", resourceCulture);
            }
        }
        
        internal static string LoadAndroidAPK {
            get {
                return ResourceManager.GetString("LoadAndroidAPK", resourceCulture);
            }
        }
        
        internal static string AndroidLoaded {
            get {
                return ResourceManager.GetString("AndroidLoaded", resourceCulture);
            }
        }
        
        internal static string SupportsLinux {
            get {
                return ResourceManager.GetString("SupportsLinux", resourceCulture);
            }
        }
        
        internal static string LinuxLoaded {
            get {
                return ResourceManager.GetString("LinuxLoaded", resourceCulture);
            }
        }
        
        internal static string SupportsMac {
            get {
                return ResourceManager.GetString("SupportsMac", resourceCulture);
            }
        }
        
        internal static string LoadMacZip {
            get {
                return ResourceManager.GetString("LoadMacZip", resourceCulture);
            }
        }
        
        internal static string MacLoaded {
            get {
                return ResourceManager.GetString("MacLoaded", resourceCulture);
            }
        }
        
        internal static string LoadAM2R11 {
            get {
                return ResourceManager.GetString("LoadAM2R11", resourceCulture);
            }
        }
        
        internal static string AM2R11Loaded {
            get {
                return ResourceManager.GetString("AM2R11Loaded", resourceCulture);
            }
        }
        
        internal static string CreateModPackage {
            get {
                return ResourceManager.GetString("CreateModPackage", resourceCulture);
            }
        }
        
        internal static string ModPackageCreated {
            get {
                return ResourceManager.GetString("ModPackageCreated", resourceCulture);
            }
        }
        
        internal static string LoadLinuxZip {
            get {
                return ResourceManager.GetString("LoadLinuxZip", resourceCulture);
            }
        }
        
        internal static string ZipArchivesFileFilter {
            get {
                return ResourceManager.GetString("ZipArchivesFileFilter", resourceCulture);
            }
        }
        
        internal static string APKFileFilter {
            get {
                return ResourceManager.GetString("APKFileFilter", resourceCulture);
            }
        }
        
        internal static string InvalidSaveDirectory {
            get {
                return ResourceManager.GetString("InvalidSaveDirectory", resourceCulture);
            }
        }
        
        internal static string YYCMacUnsupported {
            get {
                return ResourceManager.GetString("YYCMacUnsupported", resourceCulture);
            }
        }
        
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        internal static string SelectAM2R11FileDialog {
            get {
                return ResourceManager.GetString("SelectAM2R11FileDialog", resourceCulture);
            }
        }
        
        internal static string FieldsMissing {
            get {
                return ResourceManager.GetString("FieldsMissing", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string NameInvalidCharacters {
            get {
                return ResourceManager.GetString("NameInvalidCharacters", resourceCulture);
            }
        }
        
        internal static string AM2R11Invalid {
            get {
                return ResourceManager.GetString("AM2R11Invalid", resourceCulture);
            }
        }
        
        internal static string PackagingMods {
            get {
                return ResourceManager.GetString("PackagingMods", resourceCulture);
            }
        }
        
        internal static string ModPackagingAborted {
            get {
                return ResourceManager.GetString("ModPackagingAborted", resourceCulture);
            }
        }
        
        internal static string ModdedGameNotFound {
            get {
                return ResourceManager.GetString("ModdedGameNotFound", resourceCulture);
            }
        }
        
        internal static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        internal static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        internal static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        internal static string ProfileXMLFound {
            get {
                return ResourceManager.GetString("ProfileXMLFound", resourceCulture);
            }
        }
        
        internal static string SaveOSModProfile {
            get {
                return ResourceManager.GetString("SaveOSModProfile", resourceCulture);
            }
        }
        
        internal static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        internal static string SelectModdedFile {
            get {
                return ResourceManager.GetString("SelectModdedFile", resourceCulture);
            }
        }
        
        internal static string APK {
            get {
                return ResourceManager.GetString("APK", resourceCulture);
            }
        }
        
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
