//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atomic.Language {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Atomic.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string ModNotes {
            get {
                return ResourceManager.GetString("ModNotes", resourceCulture);
            }
        }
        
        public static string UsesCustomSaves {
            get {
                return ResourceManager.GetString("UsesCustomSaves", resourceCulture);
            }
        }
        
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        public static string UsesCustomMusic {
            get {
                return ResourceManager.GetString("UsesCustomMusic", resourceCulture);
            }
        }
        
        public static string UsesYYC {
            get {
                return ResourceManager.GetString("UsesYYC", resourceCulture);
            }
        }
        
        public static string BundleAndroid {
            get {
                return ResourceManager.GetString("BundleAndroid", resourceCulture);
            }
        }
        
        public static string LoadAndroidAPK {
            get {
                return ResourceManager.GetString("LoadAndroidAPK", resourceCulture);
            }
        }
        
        public static string AndroidLoaded {
            get {
                return ResourceManager.GetString("AndroidLoaded", resourceCulture);
            }
        }
        
        public static string LoadAM2R11 {
            get {
                return ResourceManager.GetString("LoadAM2R11", resourceCulture);
            }
        }
        
        public static string AM2R11Loaded {
            get {
                return ResourceManager.GetString("AM2R11Loaded", resourceCulture);
            }
        }
        
        public static string CreateModPackage {
            get {
                return ResourceManager.GetString("CreateModPackage", resourceCulture);
            }
        }
        
        public static string ModPackageCreated {
            get {
                return ResourceManager.GetString("ModPackageCreated", resourceCulture);
            }
        }
        
        public static string ZipArchivesFileFilter {
            get {
                return ResourceManager.GetString("ZipArchivesFileFilter", resourceCulture);
            }
        }
        
        public static string APKFileFilter {
            get {
                return ResourceManager.GetString("APKFileFilter", resourceCulture);
            }
        }
        
        public static string InvalidSaveDirectory {
            get {
                return ResourceManager.GetString("InvalidSaveDirectory", resourceCulture);
            }
        }
        
        public static string YYCMacUnsupported {
            get {
                return ResourceManager.GetString("YYCMacUnsupported", resourceCulture);
            }
        }
        
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        public static string SelectAM2R11FileDialog {
            get {
                return ResourceManager.GetString("SelectAM2R11FileDialog", resourceCulture);
            }
        }
        
        public static string FieldsMissing {
            get {
                return ResourceManager.GetString("FieldsMissing", resourceCulture);
            }
        }
        
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        public static string NameInvalidCharacters {
            get {
                return ResourceManager.GetString("NameInvalidCharacters", resourceCulture);
            }
        }
        
        public static string AM2R11Invalid {
            get {
                return ResourceManager.GetString("AM2R11Invalid", resourceCulture);
            }
        }
        
        public static string PackagingMods {
            get {
                return ResourceManager.GetString("PackagingMods", resourceCulture);
            }
        }
        
        public static string ModPackagingAborted {
            get {
                return ResourceManager.GetString("ModPackagingAborted", resourceCulture);
            }
        }
        
        public static string ModdedGameNotFound {
            get {
                return ResourceManager.GetString("ModdedGameNotFound", resourceCulture);
            }
        }
        
        public static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        public static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        public static string ProfileXMLFound {
            get {
                return ResourceManager.GetString("ProfileXMLFound", resourceCulture);
            }
        }
        
        public static string SaveOSModProfile {
            get {
                return ResourceManager.GetString("SaveOSModProfile", resourceCulture);
            }
        }
        
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        public static string SelectModdedFile {
            get {
                return ResourceManager.GetString("SelectModdedFile", resourceCulture);
            }
        }
        
        public static string APK {
            get {
                return ResourceManager.GetString("APK", resourceCulture);
            }
        }
        
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        public static string OSGameLoaded {
            get {
                return ResourceManager.GetString("OSGameLoaded", resourceCulture);
            }
        }
        
        public static string SupportsOS {
            get {
                return ResourceManager.GetString("SupportsOS", resourceCulture);
            }
        }
        
        public static string LoadOSZip {
            get {
                return ResourceManager.GetString("LoadOSZip", resourceCulture);
            }
        }
    }
}
