//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atomic.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atomic.Language.Text", typeof(Text).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM2R 1.1 zip is invalid! Error code:.
        /// </summary>
        public static string AM2R11Invalid {
            get {
                return ResourceManager.GetString("AM2R11Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.1 loaded!.
        /// </summary>
        public static string AM2R11Loaded {
            get {
                return ResourceManager.GetString("AM2R11Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android.
        /// </summary>
        public static string Android {
            get {
                return ResourceManager.GetString("Android", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modded APK loaded!.
        /// </summary>
        public static string AndroidLoaded {
            get {
                return ResourceManager.GetString("AndroidLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to apk.
        /// </summary>
        public static string APK {
            get {
                return ResourceManager.GetString("APK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android application packages (*.apk).
        /// </summary>
        public static string APKFileFilter {
            get {
                return ResourceManager.GetString("APKFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author(s):.
        /// </summary>
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additionally bundle Android.
        /// </summary>
        public static string BundleAndroid {
            get {
                return ResourceManager.GetString("BundleAndroid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create mod package(s).
        /// </summary>
        public static string CreateModPackage {
            get {
                return ResourceManager.GetString("CreateModPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name, author or version field missing! Mod packaging aborted..
        /// </summary>
        public static string FieldsMissing {
            get {
                return ResourceManager.GetString("FieldsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid save directory! Please consult the GameMaker: Studio 1.4 documentation for valid save directories!.
        /// </summary>
        public static string InvalidSaveDirectory {
            get {
                return ResourceManager.GetString("InvalidSaveDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language (change requires a restart).
        /// </summary>
        public static string LanguageNotice {
            get {
                return ResourceManager.GetString("LanguageNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        public static string Linux {
            get {
                return ResourceManager.GetString("Linux", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load 1.1.
        /// </summary>
        public static string LoadAM2R11 {
            get {
                return ResourceManager.GetString("LoadAM2R11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load modded Android APK.
        /// </summary>
        public static string LoadAndroidAPK {
            get {
                return ResourceManager.GetString("LoadAndroidAPK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load modded {0} .zip.
        /// </summary>
        public static string LoadOSZip {
            get {
                return ResourceManager.GetString("LoadOSZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac.
        /// </summary>
        public static string Mac {
            get {
                return ResourceManager.GetString("Mac", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modded {0} game not found, make sure it&apos;s not placed in any subfolders.\nCreated profile will likely not be installable, are you sure you want to continue?.
        /// </summary>
        public static string ModdedGameNotFound {
            get {
                return ResourceManager.GetString("ModdedGameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod name:.
        /// </summary>
        public static string ModName {
            get {
                return ResourceManager.GetString("ModName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod notes:.
        /// </summary>
        public static string ModNotes {
            get {
                return ResourceManager.GetString("ModNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod package created!.
        /// </summary>
        public static string ModPackageCreated {
            get {
                return ResourceManager.GetString("ModPackageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mod packaging aborted!.
        /// </summary>
        public static string ModPackagingAborted {
            get {
                return ResourceManager.GetString("ModPackagingAborted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name contains invalid characters! These characters are not allowed:.
        /// </summary>
        public static string NameInvalidCharacters {
            get {
                return ResourceManager.GetString("NameInvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modded {0} game loaded!.
        /// </summary>
        public static string OSGameLoaded {
            get {
                return ResourceManager.GetString("OSGameLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging mod(s)... This could take a while!.
        /// </summary>
        public static string PackagingMods {
            get {
                return ResourceManager.GetString("PackagingMods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to profile.xml found. This file is used by the AM2RLauncher to determine profile stats and its inclusion may make the profile uninstallable. Are you sure you want to continue?.
        /// </summary>
        public static string ProfileXMLFound {
            get {
                return ResourceManager.GetString("ProfileXMLFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        public static string QuitMenu {
            get {
                return ResourceManager.GetString("QuitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically fill in fields from last usage.
        /// </summary>
        public static string RememberFields {
            get {
                return ResourceManager.GetString("RememberFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save {0} mod profile.
        /// </summary>
        public static string SaveOSModProfile {
            get {
                return ResourceManager.GetString("SaveOSModProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select AM2R_1.1.zip.
        /// </summary>
        public static string SelectAM2R11FileDialog {
            get {
                return ResourceManager.GetString("SelectAM2R11FileDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        public static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your modded {0} AM2R .{1}.
        /// </summary>
        public static string SelectModdedFile {
            get {
                return ResourceManager.GetString("SelectModdedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Settings.
        /// </summary>
        public static string SettingsMenu {
            get {
                return ResourceManager.GetString("SettingsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports {0}.
        /// </summary>
        public static string SupportsOS {
            get {
                return ResourceManager.GetString("SupportsOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Language.
        /// </summary>
        public static string SystemLanguage {
            get {
                return ResourceManager.GetString("SystemLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses custom music.
        /// </summary>
        public static string UsesCustomMusic {
            get {
                return ResourceManager.GetString("UsesCustomMusic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses custom save directory.
        /// </summary>
        public static string UsesCustomSaves {
            get {
                return ResourceManager.GetString("UsesCustomSaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uses YoYo Compiler.
        /// </summary>
        public static string UsesYYC {
            get {
                return ResourceManager.GetString("UsesYYC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        public static string Windows {
            get {
                return ResourceManager.GetString("Windows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YoYoCompiler isn&apos;t supported with Mac!.
        /// </summary>
        public static string YYCMacUnsupported {
            get {
                return ResourceManager.GetString("YYCMacUnsupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Archives (*.zip).
        /// </summary>
        public static string ZipArchivesFileFilter {
            get {
                return ResourceManager.GetString("ZipArchivesFileFilter", resourceCulture);
            }
        }
    }
}
